### ISSUE TITLE
Create an archive with an empty file and a password generates an incorrect file

### ISSUE THREAD

**Issue by tbuziak** [ZipArchive/ZipArchive#301]
Hi, 
I use SSZipArchive a long time, everything was ok until the upgrade IOS10. Without changing anything in the code, my application creates a bad archive files with password. Created file can not be unpacked by the library or any external application.
The library can unzip files with password created before upgrading to iOS10!
iOS Deployment Target: 8.4

Using the library in an application for OSX, files with a password are created correctly!

**Comment by jhudsonWA** [comment]
This still an issue?

**Comment by tbuziak** [comment]
Unfortunately Yes, in iOS10.3 archive whit password, can not be unpacked.

**Comment by Coeur** [comment]
@tbuziak, I cannot reproduce this [on branch 2.0](https://github.com/ZipArchive/ZipArchive/tree/2.0) with the latest example applications (folders ObjectiveCExample or SwiftExample) that support password.

Please provide a reproducible case for this issue, so that we can determine if the issue if from your code, your files, your password, etc.

**Comment by tbuziak** [comment]
I create new project, and it works, but in production application, i have strange issue.
When create zip whiteout password, all is OK, zip and unzip.
But whit password good and wrong I can't unzip archive.

**Use good password**
```
[SSZipArchive createZipFileAtPath:backupFile
                          withContentsOfDirectory:[DB appDataPath]
                                     withPassword:sPassword]
Output:
isFilePasswordProtectedAtPath: 0
isPasswordValidForArchiveAtPath: 1
error zip: crc check failed for file
```

**Use wrong password**
```
[SSZipArchive unzipFileAtPath:backupFile
                                toDestination:tmpDir
                                    overwrite:YES
                                     password:sPassword
                                        error:&error]
Output:
isFilePasswordProtectedAtPath: 0
isPasswordValidForArchiveAtPath: 0
error zip: failed to open file in zip file
```

**Comment by tbuziak** [comment]
I found BUG.
If the archive contains empty directories and is password protected, the application returns error **crc check failed for file**

**Comment by CoderMaurice** [comment]
I have the same problem
When it returns error `crc check failed for file`
Some files will not be decompressed
Did you solve the problem?
@tbuziak

**Comment by Coeur** [comment]
It may have been fixed with #356. Can you try with SSZipArchive 2.0.2?

**Comment by CoderMaurice** [comment]
I tried the latest version, but the problem still exists @Coeur

**Comment by Coeur** [comment]
You're right. I reproduced it. This is a serious issue.

**Comment by tbuziak** [comment]
Put a file into any empty directory's before password compression and everything will be ok

**Comment by Coeur** [comment]
There is a **.DS_Store** file added already apparently, since 5492b7bceab08b7283720911fb93ac749448badd

**Comment by Coeur** [comment]
Actually, unzipping with Keka a file zipped by SSZipArchive with a password and an empty folder will give me:
>Error code 2 using "p7zip"
Fatal error

**Comment by Coeur** [comment]
OK, I got a clue!
The root of the issue is not about empty folders. The root of the issue is supporting **empty files** with password. In the case of the empty folder, it was the empty file ".DS_Store" that is causing the issue.

**Comment by Coeur** [comment]
OK, reproduced the issue in pure minizip. So I opened a ticket there: https://github.com/nmoinvaz/minizip/issues/127

**Comment by MarkYuan** [comment]
the method is not correct, i modify this method
+ (BOOL)isFilePasswordProtectedAtPath:(NSString *)path {
    // Begin opening
    BOOL needPassword = NO;
    zipFile zip = unzOpen((const char*)[path fileSystemRepresentation]);
    if (zip == NULL) {
        return needPassword;
    }
    
    int ret = unzGoToFirstFile(zip);
    if (ret == UNZ_OK) {
        do {
            ret = unzOpenCurrentFile(zip);
            if (ret != UNZ_OK) {
//                return NO;
            }
            unz_file_info fileInfo = {0};
            ret = unzGetCurrentFileInfo(zip, &fileInfo, NULL, 0, NULL, 0, NULL, 0);
            if (ret != UNZ_OK) {
//                return NO;
            } else if ((fileInfo.flag & 1) == 1) {
//                return YES;
                needPassword = YES;
            }
            
            unzCloseCurrentFile(zip);
            ret = unzGoToNextFile(zip);
        } while (ret == UNZ_OK && UNZ_OK != UNZ_END_OF_LIST_OF_FILE);
    }
    
    return needPassword;
}

**Comment by Coeur** [comment]
Unzipping empty folders/files with password should be fixed in a48f5d140acfb8f6192fa04a3500c3838dd16e41, but there may still be an issue with zipping compatibility with other applications.

**Comment by Coeur** [comment]
Zipping compatibility problematic with other apps is addressed in #228, so I'm closing this one as resolved.
