### ISSUE TITLE
Zip one file fail

### ISSUE THREAD

**Issue by veila** [ZipArchive/ZipArchive#372]
Hi, when I zip only one file, still create a file .zip, but seems it's empty. I check just 22 bytes.
I test all file as mp3, mp4, jpg,... But when I move file to a folder and zip the folder. It's works.
Pls help me.

p/s:
One more issue: If folder empty in father folder. When I unzip the father folder. sub folder which empty change type, not folder type any more

**Comment by Coeur** [comment]
I was not able to reproduce your issue.

Here are my steps:
* I cloned the https://github.com/ZipArchive/ZipArchive/tree/master/SwiftExample project
* I removed 1.md and 2.md to only keep one file
* I changed `SSZipArchive.createZipFile(atPath: zipPath!, withContentsOfDirectory: sampleDataPath` with `SSZipArchive.createZipFile(atPath: zipPath!, withFilesAtPaths: [sampleDataPath + "/mountain.png"]` to only zip one file without specifying a folder.
![screen shot 2017-09-09 at 4 42 17 pm](https://user-images.githubusercontent.com/839992/30238685-3cbec358-957e-11e7-9df6-ad8fe9d61da0.png)

It worked and the resulting zip file was 3.2 MB (original image was 3.3 MB).

So I will close this issue as I cannot reproduce it. But I can re-open it if you provide more details that could lead to a reproducible scenario. Like:
* Which version of SSZipArchive are you using?
* How did you integrate it? (CocoaPods, Carthage, Submodule, Copy-paste, etc.)
* Which version of iOS/macOS/tvOS/watchOS are you testing?
* Is it on simulator or real device? If simulator, what is your filesystem (i.e., your version of macOS)?
* Are you using ObjC or Swift?
* What lines of code are you using in your scenario?
* Do you have a sample project that can reproduce the issue?

**Comment by veila** [comment]
Thanks for you support.
I install by cocoapod for iOS version 2.0.5. It happen on both simulator and real device.
and I ussing ObjC.
Like I said, It works when I zip a folder but single file not work. I can reproduce in your sample.
if you try zip only 1.md or mountain.png, you can not unzip and return log "No success"
Hope you help me soon.
Thanks

**Comment by Coeur** [comment]
I'll reopen it, as you gave more details in your issue, but I was clearly unable to reproduce your issue.

1. I delete 1.md and 2.md
2. I run ObjectiveCExample 2.0.5 on iPhone SE Simulator iOS 11 with Xcode 9 beta 6 on macOS 10.12.6
3. I click "zip sample data" then "unzip sample data", it works, no error

Is anyone able to reproduce @veila issue?

**Comment by veila** [comment]
Is mountain.png file in the SampleData folder?
If you said delete 1.md and 2.md, so you zip sample data folder with one file in there, it works too with me.
I remove sample data folder and zip only file mountain.png, no any folder. and error

**Comment by Coeur** [comment]
@veila OK, there are two issues:

1. media (images, audio, video) outside of a **blue** folder are not packaged inside an iOS application, and that's by Apple design. It is required that assets are put in assets folders. So in your scenario, the file was not existing.

2. SSZipArchive reports incorrectly a success when files don't exist.

I'll work on the error reporting to actually report an error.

**Comment by Coeur** [comment]
fixed with https://github.com/ZipArchive/ZipArchive/commit/fa3fe1dfd8d6e31ba484a314a70b89aafe99101d
so it will be correctly reporting problems with missing files in 2.0.6

**Comment by veila** [comment]
I will update now. Thank you a lot!

**Comment by veila** [comment]
Sorry but seem this bug still there. I update pod 2.0.6. Using xcode 8.3.3, ios 10.

**Comment by Coeur** [comment]
@veila  Please clone ZipArchive and share a demonstration of the issue.

**Comment by veila** [comment]
I zip one file png.(bring it out of the Sample data folder)
`NSString *sampleDataPath = [[NSBundle mainBundle].bundleURL
                              URLByAppendingPathComponent:@"mountain.png"
                              isDirectory:NO].path;
  _zipPath = [self tempZipPath];
  NSString *password = _passwordField.text;
  BOOL success = [SSZipArchive createZipFileAtPath:_zipPath
                           withContentsOfDirectory:sampleDataPath
                                      withPassword:password.length > 0 ? password : nil];`

And in Caches Document the zip file only 22 byte and can not unzip. 

<img width="712" alt="screen shot 2017-09-14 at 09 50 37" src="https://user-images.githubusercontent.com/13691373/30409960-68821622-9932-11e7-8fc9-96b250446baa.png">

<img width="392" alt="screen shot 2017-09-14 at 09 51 05" src="https://user-images.githubusercontent.com/13691373/30409963-6ceb9b52-9932-11e7-96b0-66e508b55a8c.png">

**Comment by Coeur** [comment]
@veila, but `success` is `@NO`, isn't it? It correctly reported that it failed to make an archive with a missing file, isn't it?

And please re-read what I wrote above:
>media (images, audio, video) outside of a **blue** folder are not packaged inside an iOS application, and that's by Apple design. It is required that assets are put in assets folders. **So in your scenario, the [image] file was not existing.**

**Comment by veila** [comment]
Ok Thanks, I understanded
