### ISSUE TITLE
Unzip fails if AddressSanitizer is turned on

### ISSUE THREAD

**Issue by aoverholtzer** [ZipArchive/ZipArchive#457]
If you have the AddressSanitizer diagnostic turned on in your scheme, unzip consistently fails at unzip.c line 1347:

```
==33351==ERROR: AddressSanitizer: memcpy-param-overlap: memory ranges [0x63100012c800,0x63100013c493) and [0x63100012cb6c, 0x63100013c7ff) overlap
    #0 0x10201a6a1 in __asan_memcpy (libclang_rt.asan_iossim_dynamic.dylib:x86_64+0x4d6a1)
    #1 0x101948b9a in unzReadCurrentFile unzip.c:1347
    #2 0x10192ceca in +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] SSZipArchive.m:452
    ...
```

This is reproducible with the ObjectiveCExample sample project:

1. Edit the ObjectiveCExample_iOS scheme
2. Select Run > Diagnostics
3. Check the “Address Sanitizer” box
4. Run the project and attempt to unzip

Workaround is to turn off AddressSanitizer.

**Comment by Coeur** [comment]
Fixed on master with 6866ad618c73d9b3b73ee0c922a8ce9e3493a061

**Comment by mobileben** [comment]
@Coeur is this confirmed as fixed? I just pulled from master as I was getting a memory-param-overlap. I still get this, albeit in a different location this time.

=================================================================
[1m[31m==40007==ERROR: AddressSanitizer: memcpy-param-overlap: memory ranges [0x6310002e4800,0x6310002f4649) and [0x6310002e49b6, 0x6310002f47ff) overlap
[1m[0m    #0 0x122dbc5d1 in __asan_memcpy (libclang_rt.asan_iossim_dynamic.dylib:x86_64+0x505d1)
    #1 0x1059804b3 in unzReadCurrentFile (ZipArchive:x86_64+0x2a4b3)
    #2 0x105994101 in +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] (ZipArchive:x86_64+0x3e101)
    #3 0x1059923a9 in +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:password:error:delegate:progressHandler:completionHandler:] (ZipArchive:x86_64+0x3c3a9)
    #4 0x105991ecb in +[SSZipArchive unzipFileAtPath:toDestination:overwrite:password:error:] (ZipArchive:x86_64+0x3becb)
    #5 0x100e9d4d8  (JKS:x86_64+0x10007e4d8)
    #6 0x1014a8fa8  (JKS:x86_64+0x100689fa8)
    #7 0x122dbe045 in __wrap_dispatch_async_block_invoke (libclang_rt.asan_iossim_dynamic.dylib:x86_64+0x52045)
    #8 0x109b01594 in _dispatch_call_block_and_release (libdispatch.dylib:x86_64+0x3594)
    #9 0x109b02601 in _dispatch_client_callout (libdispatch.dylib:x86_64+0x4601)
    #10 0x109b09b0a in _dispatch_lane_serial_drain (libdispatch.dylib:x86_64+0xbb0a)
    #11 0x109b0a783 in _dispatch_lane_invoke (libdispatch.dylib:x86_64+0xc783)
    #12 0x109b14899 in _dispatch_workloop_worker_thread (libdispatch.dylib:x86_64+0x16899)
    #13 0x109eedfd1 in _pthread_wqthread (libsystem_pthread.dylib:x86_64+0x2fd1)
    #14 0x109eedbe8 in start_wqthread (libsystem_pthread.dylib:x86_64+0x2be8)
    #15 0x70001028ab3f  (<unknown module>)

[1m[32m0x6310002e4800 is located 0 bytes inside of 65535-byte region [0x6310002e4800,0x6310002f47ff)
[1m[0m[1m[35mallocated by thread T21 here:[1m[0m
    #0 0x122dbf1c3 in wrap_malloc (libclang_rt.asan_iossim_dynamic.dylib:x86_64+0x531c3)
    #1 0x10597f2d1 in unzOpenCurrentFile3 (ZipArchive:x86_64+0x292d1)
    #2 0x105993125 in +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] (ZipArchive:x86_64+0x3d125)
    #3 0x1059923a9 in +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:password:error:delegate:progressHandler:completionHandler:] (ZipArchive:x86_64+0x3c3a9)
    #4 0x105991ecb in +[SSZipArchive unzipFileAtPath:toDestination:overwrite:password:error:] (ZipArchive:x86_64+0x3becb)
    #5 0x100e9d4d8  (JKS:x86_64+0x10007e4d8)
    #6 0x1014a8fa8  (JKS:x86_64+0x100689fa8)
    #7 0x122dbe045 in __wrap_dispatch_async_block_invoke (libclang_rt.asan_iossim_dynamic.dylib:x86_64+0x52045)
    #8 0x109b01594 in _dispatch_call_block_and_release (libdispatch.dylib:x86_64+0x3594)
    #9 0x109b02601 in _dispatch_client_callout (libdispatch.dylib:x86_64+0x4601)
    #10 0x109b09b0a in _dispatch_lane_serial_drain (libdispatch.dylib:x86_64+0xbb0a)
    #11 0x109b0a783 in _dispatch_lane_invoke (libdispatch.dylib:x86_64+0xc783)
    #12 0x109b14899 in _dispatch_workloop_worker_thread (libdispatch.dylib:x86_64+0x16899)
    #13 0x109eedfd1 in _pthread_wqthread (libsystem_pthread.dylib:x86_64+0x2fd1)
    #14 0x109eedbe8 in start_wqthread (libsystem_pthread.dylib:x86_64+0x2be8)
    #15 0x70001028ab3f  (<unknown module>)

Thread T21 created by T0 here:
    <empty stack>

[1m[32m0x6310002e49b6 is located 438 bytes inside of 65535-byte region [0x6310002e4800,0x6310002f47ff)
[1m[0m[1m[35mallocated by thread T21 here:[1m[0m
    #0 0x122dbf1c3 in wrap_malloc (libclang_rt.asan_iossim_dynamic.dylib:x86_64+0x531c3)
    #1 0x10597f2d1 in unzOpenCurrentFile3 (ZipArchive:x86_64+0x292d1)
    #2 0x105993125 in +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] (ZipArchive:x86_64+0x3d125)
    #3 0x1059923a9 in +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:password:error:delegate:progressHandler:completionHandler:] (ZipArchive:x86_64+0x3c3a9)
    #4 0x105991ecb in +[SSZipArchive unzipFileAtPath:toDestination:overwrite:password:error:] (ZipArchive:x86_64+0x3becb)
    #5 0x100e9d4d8  (JKS:x86_64+0x10007e4d8)
    #6 0x1014a8fa8  (JKS:x86_64+0x100689fa8)
    #7 0x122dbe045 in __wrap_dispatch_async_block_invoke (libclang_rt.asan_iossim_dynamic.dylib:x86_64+0x52045)
    #8 0x109b01594 in _dispatch_call_block_and_release (libdispatch.dylib:x86_64+0x3594)
    #9 0x109b02601 in _dispatch_client_callout (libdispatch.dylib:x86_64+0x4601)
    #10 0x109b09b0a in _dispatch_lane_serial_drain (libdispatch.dylib:x86_64+0xbb0a)
    #11 0x109b0a783 in _dispatch_lane_invoke (libdispatch.dylib:x86_64+0xc783)
    #12 0x109b14899 in _dispatch_workloop_worker_thread (libdispatch.dylib:x86_64+0x16899)
    #13 0x109eedfd1 in _pthread_wqthread (libsystem_pthread.dylib:x86_64+0x2fd1)
    #14 0x109eedbe8 in start_wqthread (libsystem_pthread.dylib:x86_64+0x2be8)
    #15 0x70001028ab3f  (<unknown module>)

SUMMARY: AddressSanitizer: memcpy-param-overlap (libclang_rt.asan_iossim_dynamic.dylib:x86_64+0x505d1) in __asan_memcpy
2019-02-21 16:49:31.215070-0800 JKS[40007:638203] =================================================================
2019-02-21 16:49:31.215390-0800 JKS[40007:638203] ==40007==ERROR: AddressSanitizer: memcpy-param-overlap: memory ranges [0x6310002e4800,0x6310002f4649) and [0x6310002e49b6, 0x6310002f47ff) overlap
2019-02-21 16:49:31.215574-0800 JKS[40007:638203]     #0 0x122dbc5d1 in __asan_memcpy (libclang_rt.asan_iossim_dynamic.dylib:x86_64+0x505d1)
2019-02-21 16:49:31.215747-0800 JKS[40007:638203]     #1 0x1059804b3 in unzReadCurrentFile (ZipArchive:x86_64+0x2a4b3)
2019-02-21 16:49:31.215939-0800 JKS[40007:638203]     #2 0x105994101 in +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] (ZipArchive:x86_64+0x3e101)
2019-02-21 16:49:31.216123-0800 JKS[40007:638203]     #3 0x1059923a9 in +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:password:error:delegate:progressHandler:completionHandler:] (ZipArchive:x86_64+0x3c3a9)
2019-02-21 16:49:31.216280-0800 JKS[40007:638203]     #4 0x105991ecb in +[SSZipArchive unzipFileAtPath:toDestination:overwrite:password:error:] (ZipArchive:x86_64+0x3becb)
2019-02-21 16:49:31.216428-0800 JKS[40007:638203]     #5 0x100e9d4d8  (JKS:x86_64+0x10007e4d8)
2019-02-21 16:49:31.216587-0800 JKS[40007:638203]     #6 0x1014a8fa8  (JKS:x86_64+0x100689fa8)
2019-02-21 16:49:31.216734-0800 JKS[40007:638203]     #7 0x122dbe045 in __wrap_dispatch_async_block_invoke (libclang_rt.asan_iossim_dynamic.dylib:x86_64+0x52045)
2019-02-21 16:49:31.216972-0800 JKS[40007:638203]     #8 0x109b01594 in _dispatch_call_block_and_release (libdispatch.dylib:x86_64+0x3594)
2019-02-21 16:49:31.217271-0800 JKS[40007:638203]     #9 0x109b02601 in _dispatch_client_callout (libdispatch.dylib:x86_64+0x4601)
2019-02-21 16:49:31.217600-0800 JKS[40007:638203]     #10 0x109b09b0a in _dispatch_lane_serial_drain (libdispatch.dylib:x86_64+0xbb0a)
2019-02-21 16:49:31.217889-0800 JKS[40007:638203]     #11 0x109b0a783 in _dispatch_lane_invoke (libdispatch.dylib:x86_64+0xc783)
2019-02-21 16:49:31.218140-0800 JKS[40007:638203]     #12 0x109b14899 in _dispatch_workloop_worker_thread (libdispatch.dylib:x86_64+0x16899)
2019-02-21 16:49:31.218397-0800 JKS[40007:638203]     #13 0x109eedfd1 in _pthread_wqthread (libsystem_pthread.dylib:x86_64+0x2fd1)
2019-02-21 16:49:31.218612-0800 JKS[40007:638203]     #14 0x109eedbe8 in start_wqthread (libsystem_pthread.dylib:x86_64+0x2be8)
2019-02-21 16:49:31.218827-0800 JKS[40007:638203]     #15 0x70001028ab3f  (<unknown module>)
2019-02-21 16:49:31.219115-0800 JKS[40007:638203] 
2019-02-21 16:49:31.219298-0800 JKS[40007:638203] 0x6310002e4800 is located 0 bytes inside of 65535-byte region [0x6310002e4800,0x6310002f47ff)
2019-02-21 16:49:31.219559-0800 JKS[40007:638203] allocated by thread T21 here:
2019-02-21 16:49:31.219869-0800 JKS[40007:638203]     #0 0x122dbf1c3 in wrap_malloc (libclang_rt.asan_iossim_dynamic.dylib:x86_64+0x531c3)
2019-02-21 16:49:31.220085-0800 JKS[40007:638203]     #1 0x10597f2d1 in unzOpenCurrentFile3 (ZipArchive:x86_64+0x292d1)
2019-02-21 16:49:31.220266-0800 JKS[40007:638203]     #2 0x105993125 in +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] (ZipArchive:x86_64+0x3d125)
2019-02-21 16:49:31.220507-0800 JKS[40007:638203]     #3 0x1059923a9 in +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:password:error:delegate:progressHandler:completionHandler:] (ZipArchive:x86_64+0x3c3a9)
2019-02-21 16:49:31.220795-0800 JKS[40007:638203]     #4 0x105991ecb in +[SSZipArchive unzipFileAtPath:toDestination:overwrite:password:error:] (ZipArchive:x86_64+0x3becb)
2019-02-21 16:49:31.220921-0800 JKS[40007:638203]     #5 0x100e9d4d8  (JKS:x86_64+0x10007e4d8)
2019-02-21 16:49:31.221141-0800 JKS[40007:638203]     #6 0x1014a8fa8  (JKS:x86_64+0x100689fa8)
2019-02-21 16:49:31.221344-0800 JKS[40007:638203]     #7 0x122dbe045 in __wrap_dispatch_async_block_invoke (libclang_rt.asan_iossim_dynamic.dylib:x86_64+0x52045)
2019-02-21 16:49:31.221608-0800 JKS[40007:638203]     #8 0x109b01594 in _dispatch_call_block_and_release (libdispatch.dylib:x86_64+0x3594)
2019-02-21 16:49:31.221770-0800 JKS[40007:638203]     #9 0x109b02601 in _dispatch_client_callout (libdispatch.dylib:x86_64+0x4601)
2019-02-21 16:49:31.222026-0800 JKS[40007:638203]     #10 0x109b09b0a in _dispatch_lane_serial_drain (libdispatch.dylib:x86_64+0xbb0a)
2019-02-21 16:49:31.222265-0800 JKS[40007:638203]     #11 0x109b0a783 in _dispatch_lane_invoke (libdispatch.dylib:x86_64+0xc783)
2019-02-21 16:49:31.222456-0800 JKS[40007:638203]     #12 0x109b14899 in _dispatch_workloop_worker_thread (libdispatch.dylib:x86_64+0x16899)
2019-02-21 16:49:31.230446-0800 JKS[40007:638203]     #13 0x109eedfd1 in _pthread_wqthread (libsystem_pthread.dylib:x86_64+0x2fd1)
2019-02-21 16:49:31.230618-0800 JKS[40007:638203]     #14 0x109eedbe8 in start_wqthread (libsystem_pthread.dylib:x86_64+0x2be8)
2019-02-21 16:49:31.230777-0800 JKS[40007:638203]     #15 0x70001028ab3f  (<unknown module>)
2019-02-21 16:49:31.230939-0800 JKS[40007:638203] 
2019-02-21 16:49:31.231120-0800 JKS[40007:638203] Thread T21 created by T0 here:
2019-02-21 16:49:31.231297-0800 JKS[40007:638203]     <empty stack>
2019-02-21 16:49:31.231468-0800 JKS[40007:638203] 
2019-02-21 16:49:31.231605-0800 JKS[40007:638203] 0x6310002e49b6 is located 438 bytes inside of 65535-byte region [0x6310002e4800,0x6310002f47ff)
2019-02-21 16:49:31.231762-0800 JKS[40007:638203] allocated by thread T21 here:
2019-02-21 16:49:31.231939-0800 JKS[40007:638203]     #0 0x122dbf1c3 in wrap_malloc (libclang_rt.asan_iossim_dynamic.dylib:x86_64+0x531c3)
2019-02-21 16:49:31.232058-0800 JKS[40007:638203]     #1 0x10597f2d1 in unzOpenCurrentFile3 (ZipArchive:x86_64+0x292d1)
2019-02-21 16:49:31.233159-0800 JKS[40007:638203]     #2 0x105993125 in +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] (ZipArchive:x86_64+0x3d125)
2019-02-21 16:49:31.233266-0800 JKS[40007:638203]     #3 0x1059923a9 in +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:password:error:delegate:progressHandler:completionHandler:] (ZipArchive:x86_64+0x3c3a9)
2019-02-21 16:49:31.233372-0800 JKS[40007:638203]     #4 0x105991ecb in +[SSZipArchive unzipFileAtPath:toDestination:overwrite:password:error:] (ZipArchive:x86_64+0x3becb)
2019-02-21 16:49:31.233503-0800 JKS[40007:638203]     #5 0x100e9d4d8  (JKS:x86_64+0x10007e4d8)
2019-02-21 16:49:31.233620-0800 JKS[40007:638203]     #6 0x1014a8fa8  (JKS:x86_64+0x100689fa8)
2019-02-21 16:49:31.233744-0800 JKS[40007:638203]     #7 0x122dbe045 in __wrap_dispatch_async_block_invoke (libclang_rt.asan_iossim_dynamic.dylib:x86_64+0x52045)
2019-02-21 16:49:31.234044-0800 JKS[40007:638203]     #8 0x109b01594 in _dispatch_call_block_and_release (libdispatch.dylib:x86_64+0x3594)
2019-02-21 16:49:31.234138-0800 JKS[40007:638203]     #9 0x109b02601 in _dispatch_client_callout (libdispatch.dylib:x86_64+0x4601)
2019-02-21 16:49:31.234259-0800 JKS[40007:638203]     #10 0x109b09b0a in _dispatch_lane_serial_drain (libdispatch.dylib:x86_64+0xbb0a)
2019-02-21 16:49:31.234368-0800 JKS[40007:638203]     #11 0x109b0a783 in _dispatch_lane_invoke (libdispatch.dylib:x86_64+0xc783)
2019-02-21 16:49:31.234490-0800 JKS[40007:638203]     #12 0x109b14899 in _dispatch_workloop_worker_thread (libdispatch.dylib:x86_64+0x16899)
2019-02-21 16:49:31.234607-0800 JKS[40007:638203]     #13 0x109eedfd1 in _pthread_wqthread (libsystem_pthread.dylib:x86_64+0x2fd1)
2019-02-21 16:49:31.234720-0800 JKS[40007:638203]     #14 0x109eedbe8 in start_wqthread (libsystem_pthread.dylib:x86_64+0x2be8)
2019-02-21 16:49:31.234813-0800 JKS[40007:638203]     #15 0x70001028ab3f  (<unknown module>)
2019-02-21 16:49:31.235289-0800 JKS[40007:638203] 
2019-02-21 16:49:31.235411-0800 JKS[40007:638203] SUMMARY: AddressSanitizer: memcpy-param-overlap (libclang_rt.asan_iossim_dynamic.dylib:x86_64+0x505d1) in __asan_memcpy
2019-02-21 16:49:31.235519-0800 JKS[40007:638203]

**Comment by mobileben** [comment]
This was running under Release, I'm currently rebuilding for Debug to see if this gives me more accurate line (since it triggered at a variable assignment) number.

**Comment by mobileben** [comment]
I get this under Release, but not Debug
